[package]
name = "cognyx-bus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
sha2 = { workspace = true }
ed25519-dalek = { workspace = true }
rand = { workspace = true }
dashmap = { workspace = true }
async-trait = { workspace = true }
tokio-stream = { workspace = true }
cognyx-proto = { workspace = true }


[[bin]]
name = "cognyx-bus"
path = "src/main.rs"
