[package]
name = "cognyx-ai-embedding"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
tokio = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
cognyx-proto = { workspace = true }
cognyx-sdk = { workspace = true }

[[bin]]
name = "cognyx-ai-embedding"
path = "src/main.rs"
